/**
 * src/profiles/plain/index.ts  — AUTO-GENERATED + CURATED.
 *
 * Base generated by tools/generate_plain_profile.py from:
 *   - entities-config.ts     (12 entity types)
 *   - submission-config.ts   (110 form fields, 10 processes)
 *   - submission-value-pairs.ts
 *
 * "plain" profile — generic DSpace CRIS 4Science baseline.
 *
 * Config files for this profile live at:
 *   src/profiles/plain/config/authority-relations.ts
 *   src/profiles/plain/config/entities-config.ts
 *   src/profiles/plain/config/submission-config.ts
 *   src/profiles/plain/config/submission-value-pairs.ts
 *   src/profiles/plain/config/metadata-registry-config.ts
 *   src/profiles/plain/config/controlled-vocabulary-config.ts
 */

import type { ProfileConfig } from "../profile-config";

const plainProfile: ProfileConfig = {
  key: "plain",
  displayName: "DSpace CRIS (Plain)",

  theme: {
    appName: "DSpace CRIS",
  },

  navTabs: [
    { key: "dashboard",   label: "Dashboard",   route: "#/dashboard" },
    { key: "communities", label: "Communities", route: "#/communities" },
    { key: "quicklinks",  label: "Quicklinks",  route: "#/quicklinks" },
    { key: "workspace",   label: "Workspace",   route: "#/workspace" },
    { key: "search",      label: "Search",      route: "#/search" },
  ],

  dashboard: {
    clusterSource: "ts",
  },

  entityClusters: [
    {
      key: "research",
      label: "Research",
      description: "Research outputs and activities",
      entityTypes: [
        "Publication",
        "Project",
        "Funding",
        "Equipment",
        "Event",
        "Patent",
        "Product",
      ],
    },
    {
      key: "people-orgs",
      label: "People & Organisations",
      description: "Authority entities",
      entityTypes: ["Person", "OrgUnit"],
    },
    {
      key: "reference",
      label: "Reference",
      description: "Controlled reference entities",
      entityTypes: ["Journal", "JournalVolume", "JournalIssue"],
    },
  ],

  quicklinks: {
    presetSource: "ts",
  },

  quicklinkPresets: [
    {
      key: "publication",
      label: "Publications",
      description: "Publications filtered by type and date.",
      baseFilters: {
        entityType: ["Publication"]
      },
      filters: [
        { key: "dc.type",        label: "Type",             facetName: "dc.type" },
        { key: "dc.date.issued", label: "Publication date", facetName: "dc.date.issued", kind: "date" },
      ],
      sort_order: 1,
      enabled: true,
    },
    {
      key: "project",
      label: "Projects",
      description: "Projects filtered by coordinator, status, and dates.",
      baseFilters: {
        entityType: ["Project"]
      },
      filters: [
        { key: "crispj.investigator",          label: "Project coordinator",   facetName: "crispj.investigator" },
        { key: "crispj.coordinator",           label: "Consortium coordinator",facetName: "crispj.coordinator" },
        { key: "oairecerif.project.startdate", label: "Start date",            facetName: "oairecerif.project.startdate", kind: "date" },
        { key: "oairecerif.project.enddate",   label: "End date",              facetName: "oairecerif.project.enddate",   kind: "date" },
      ],
      sort_order: 2,
      enabled: true,
    },
    {
      key: "funding",
      label: "Funding",
      description: "Funding items filtered by type and investigator.",
      baseFilters: {
        entityType: ["Funding"]
      },
      filters: [
        { key: "dc.type",               label: "Type",        facetName: "dc.type" },
        { key: "oairecerif.funder",     label: "Funder",      facetName: "oairecerif.funder" },
        { key: "crisfund.investigators",label: "Investigator", facetName: "crisfund.investigators" },
      ],
      sort_order: 3,
      enabled: true,
    },
    {
      key: "person",
      label: "People",
      description: "Person entities filtered by affiliation.",
      baseFilters: {
        entityType: ["Person"]
      },
      filters: [
        { key: "person.affiliation.name", label: "Affiliation", facetName: "person.affiliation.name" },
      ],
      sort_order: 4,
      enabled: true,
    },
    {
      key: "orgunit",
      label: "Organisations",
      description: "Organisational units filtered by type and country.",
      baseFilters: {
        entityType: ["OrgUnit"]
      },
      filters: [
        { key: "dc.type",                               label: "Type",    facetName: "dc.type" },
        { key: "organization.address.addresscountry",  label: "Country", facetName: "organization.address.addresscountry" },
        { key: "organization.address.addresslocality", label: "City",    facetName: "organization.address.addresslocality" },
      ],
      sort_order: 5,
      enabled: true,
    },
    {
      key: "event",
      label: "Events",
      description: "Events filtered by type and dates.",
      baseFilters: {
        entityType: ["Event"]
      },
      filters: [
        { key: "dc.type",                    label: "Type",      facetName: "dc.type" },
        { key: "crisevent.organizerou",      label: "Organizer", facetName: "crisevent.organizerou" },
        { key: "oairecerif.event.startdate", label: "Start",     facetName: "oairecerif.event.startdate", kind: "date" },
        { key: "oairecerif.event.enddate",   label: "End",       facetName: "oairecerif.event.enddate",   kind: "date" },
      ],
      sort_order: 6,
      enabled: true,
    },
    {
      key: "equipment",
      label: "Equipment",
      description: "Equipment entities filtered by type.",
      baseFilters: {
        entityType: ["Equipment"]
      },
      filters: [
        { key: "dc.type",              label: "Type",  facetName: "dc.type" },
        { key: "crisequipment.ownerou",label: "Owner", facetName: "crisequipment.ownerou" },
      ],
      sort_order: 7,
      enabled: true,
    },
    {
      key: "patent",
      label: "Patents",
      description: "Patent entities filtered by kind and dates.",
      baseFilters: {
        entityType: ["Patent"]
      },
      filters: [
        { key: "crispatent.kind",        label: "Kind",     facetName: "crispatent.kind" },
        { key: "dcterms.datesubmitted",  label: "Filed",    facetName: "dcterms.datesubmitted", kind: "date" },
        { key: "dcterms.dateaccepted",   label: "Approved", facetName: "dcterms.dateaccepted",  kind: "date" },
      ],
      sort_order: 8,
      enabled: true,
    },
    {
      key: "product",
      label: "Products / Datasets",
      description: "Product and dataset entities.",
      baseFilters: {
        entityType: ["Product"]
      },
      filters: [
        { key: "dc.type",       label: "Type", facetName: "dc.type" },
        { key: "dc.date.issued",label: "Date", facetName: "dc.date.issued", kind: "date" },
      ],
      sort_order: 9,
      enabled: true,
    },
    {
      key: "journal",
      label: "Journals",
      description: "Journal entities.",
      baseFilters: {
        entityType: ["Journal"]
      },
      filters: [
        { key: "dc.publisher", label: "Publisher", facetName: "dc.publisher" },
      ],
      sort_order: 10,
      enabled: true,
    },
  ],

  collectionMapping: {
    rulesSource: "ts",
  },

  // Collection UUIDs are instance-specific — configure via Django API
  // or override in a deployment-specific profile.
  collectionRules: [],

  fieldLabelOverrides: {
    "cris.policy.eperson": "Eperson Policy",
    "cris.policy.group": "Group Policy",
    "crisequipment.ownerou": "Owner (Organisations)",
    "crisequipment.ownerrp": "Owner (Persons)",
    "crisevent.organizerou": "Organizer(s) of the Event",
    "crisevent.organizerpj": "Organizer(s) of the Event (project)",
    "crisevent.partnerou": "Partner(s) of the Event",
    "crisevent.partnerpj": "Partner(s) of the Event (project)",
    "crisevent.sponsorou": "Sponsor(s) of the Event",
    "crisevent.sponsorpj": "Sponsor(s) of the Event (project)",
    "crisfund.award.uri": "Award URI",
    "crisfund.award.url": "Award Url",
    "crisfund.coinvestigators": "Co-Investigator(s)",
    "crisfund.investigators": "Investigator(s)",
    "crisfund.leadcoorganizations": "Lead Co-Organization(s)",
    "crisfund.leadorganizations": "Lead Organization(s)",
    "crisou.boards": "Scientifics Board",
    "crispatent.document.description": "Abstract",
    "crispatent.kind": "Kind Code",
    "crispj.coinvestigators": "Co-Investigator(s)",
    "crispj.coordinator": "Consortium Coordinator(s)",
    "crispj.investigator": "Project Coordinator",
    "crispj.openaireid": "OpenAIRE ID",
    "crispj.organization": "Participant Organization(s)",
    "crispj.partnerou": "Partner Organization(s)",
    "crisrp.education": "Organisation name",
    "crisrp.education.end": "End Date",
    "crisrp.education.start": "Start Date",
    "crisrp.name": "Fullname",
    "crisrp.name.translated": "Vernacular Name",
    "crisrp.name.variant": "Variants",
    "crisrp.qualification": "Organisation name",
    "crisrp.qualification.end": "End Date",
    "crisrp.qualification.start": "Start Date",
    "crisrp.workgroup": "Working group(s)",
    "datacite.subject.fos": "Fields of Science and Technology (OECD)",
    "dc.date.issued": "Publication Date",
    "dc.description": "Other information",
    "dc.description.sponsorship": "Sponsors",
    "dc.identifier": "Identifiers",
    "dc.identifier.applicationnumber": "Application Number",
    "dc.identifier.patentno": "Patent Number",
    "dc.language.iso": "Language",
    "dc.relation.equipment": "Generated by",
    "dc.relation.ispartofseries": "Series/Report No.",
    "dc.relation.journal": "Journal or Serie",
    "dc.relation.patent": "Predecessor",
    "dc.relation.product": "Dataset or product",
    "dc.relation.project": "Projects",
    "dc.subject": "Subject Keywords",
    "dc.title.alternative": "Other Titles",
    "dcterms.dateaccepted": "Approval Date",
    "dcterms.datesubmitted": "Registration Date",
    "dcterms.rightsholder": "Holder",
    "oaire.citation.endpage": "End Page",
    "oaire.citation.startpage": "Start Page",
    "oairecerif.acronym": "Acronym or short form of title",
    "oairecerif.affiliation.enddate": "End Date",
    "oairecerif.affiliation.startdate": "Start Date",
    "oairecerif.event.enddate": "End date",
    "oairecerif.event.place": "Location",
    "oairecerif.event.startdate": "Start date",
    "oairecerif.funding.enddate": "End date",
    "oairecerif.funding.identifier": "Grant number",
    "oairecerif.funding.startdate": "Start date",
    "oairecerif.fundingparent": "Program",
    "oairecerif.identifier.url": "Website(s)",
    "oairecerif.internalid": "Internal project ID",
    "oairecerif.oamandate": "OA Mandate",
    "oairecerif.oamandate.url": "OA Policy URL",
    "oairecerif.project.enddate": "Expected Completion",
    "oairecerif.project.startdate": "Start date",
    "organization.address.addresscountry": "Country",
    "organization.address.addresslocality": "City",
    "organization.foundingdate": "Established",
    "organization.identifier": "Identifiers",
    "organization.parentorganization": "Parent Organisation",
    "person.affiliation.name": "Main Affiliation",
    "person.birthdate": "Birth Date",
    "person.familyname": "Family name",
    "person.givenname": "First name",
    "person.identifier.rid": "Researcher ID",
    "person.jobtitle": "Job Title",
    "person.knowslanguage": "Written Language(s)",
  },

  // Plain profile uses standard DSpace submission workflow — no custom modals.
  modalRegistry: [],

  features: {
    quicklinks:     true,
    communities:    true,
    workspace:      true,
    adminClusters:  true,
    creationModals: false,
  },
};

export default plainProfile;
