export type ReciprocalRelation = {
  entityType: string;
  field: string;
  reciprocalField: string;
  reciprocalEntityType?: string;
  note?: string;
};

export type AuthorityFieldConfig = {
  field: string;
  plugin: string;
  presentation?: string;
  controlled: boolean;
  externalSource?: string;
  category?: string;
};

export const RECIPROCAL_RELATIONS: ReciprocalRelation[] = [
  {
    entityType: "Publication",
    field: "dc.relation.product",
    reciprocalField: "dc.relation.publication",
    reciprocalEntityType: "Product",
  },
  {
    entityType: "Product",
    field: "dc.relation.publication",
    reciprocalField: "dc.relation.product",
    reciprocalEntityType: "Publication",
  },
  {
    entityType: "Product",
    field: "dcat.mdw.isInDataCatalog",
    reciprocalField: "dcat.dataset",
    reciprocalEntityType: "DataCatalog",
    note: "DataCatalog - Product",
  },
  {
    entityType: "DataCatalog",
    field: "dcat.dataset",
    reciprocalField: "dcat.mdw.isInDataCatalog",
    reciprocalEntityType: "Product",
    note: "DataCatalog - Product",
  },
  {
    entityType: "Product",
    field: "dcat.distribution",
    reciprocalField: "dcat.mdw.relatedDataset",
    reciprocalEntityType: "Product",
    note: "Product - Product (Type:Distribution)",
  },
  {
    entityType: "Product",
    field: "dcat.mdw.relatedDataset",
    reciprocalField: "dcat.distribution",
    reciprocalEntityType: "Product",
    note: "Product - Product (Type:Distribution)",
  },
  {
    entityType: "Product",
    field: "dcat.mdw.servedByDataService",
    reciprocalField: "dcat.servesDataset",
    reciprocalEntityType: "DataService",
    note: "Product - DataService",
  },
  {
    entityType: "DataService",
    field: "dcat.servesDataset",
    reciprocalField: "dcat.mdw.servedByDataService",
    reciprocalEntityType: "Product",
    note: "Product - DataService",
  },
  {
    entityType: "DataCatalog",
    field: "dcat.service",
    reciprocalField: "dcat.mdw.isInDataCatalog",
    reciprocalEntityType: "DataService",
    note: "DataCatalog - DataService",
  },
  {
    entityType: "DataService",
    field: "dcat.mdw.isInDataCatalog",
    reciprocalField: "dcat.service",
    reciprocalEntityType: "DataCatalog",
    note: "DataCatalog - DataService",
  },
  {
    entityType: "Product",
    field: "dcat.mdw.containsDataset",
    reciprocalField: "dcat.inSeries",
    reciprocalEntityType: "Product",
    note: "Product (Type:DatasetSeries) - Product (Type:Dataset)",
  },
  {
    entityType: "Product",
    field: "dcat.inSeries",
    reciprocalField: "dcat.mdw.containsDataset",
    reciprocalEntityType: "Product",
    note: "Product (Type:DatasetSeries) - Product (Type:Dataset)",
  },
  {
    entityType: "Person",
    field: "mdwrepo.isOrWasStudentOf",
    reciprocalField: "mdwrepo.hasOrHadStudent",
    reciprocalEntityType: "Person",
    note: "Memorial Book Student / Teacher",
  },
  {
    entityType: "Person",
    field: "mdwrepo.hasOrHadStudent",
    reciprocalField: "mdwrepo.isOrWasStudentOf",
    reciprocalEntityType: "Person",
    note: "Memorial Book Student / Teacher",
  },
  {
    entityType: "ArchivalResource",
    field: "mdwrepo.archivalresource.parent",
    reciprocalField: "mdwrepo.archivalresource.child",
    reciprocalEntityType: "ArchivalResource",
    note: "ArchivalResource hierarchy",
  },
  {
    entityType: "ArchivalResource",
    field: "mdwrepo.archivalresource.child",
    reciprocalField: "mdwrepo.archivalresource.parent",
    reciprocalEntityType: "ArchivalResource",
    note: "ArchivalResource hierarchy",
  },
  {
    entityType: "ConceptScheme",
    field: "skos.hasTopConcept",
    reciprocalField: "skos.topConceptOf",
    reciprocalEntityType: "Concept",
    note: "SKOS hasTopConcept / topConceptOf",
  },
  {
    entityType: "Concept",
    field: "skos.topConceptOf",
    reciprocalField: "skos.hasTopConcept",
    reciprocalEntityType: "ConceptScheme",
    note: "SKOS hasTopConcept / topConceptOf",
  },
  {
    entityType: "Concept",
    field: "skos.broader",
    reciprocalField: "skos.narrower",
    reciprocalEntityType: "Concept",
    note: "SKOS broader / narrower",
  },
  {
    entityType: "Concept",
    field: "skos.narrower",
    reciprocalField: "skos.broader",
    reciprocalEntityType: "Concept",
    note: "SKOS broader / narrower",
  },
  {
    entityType: "Concept",
    field: "skos.broaderTransitive",
    reciprocalField: "skos.narrowerTransitive",
    reciprocalEntityType: "Concept",
    note: "SKOS broaderTransitive / narrowerTransitive",
  },
  {
    entityType: "Concept",
    field: "skos.narrowerTransitive",
    reciprocalField: "skos.broaderTransitive",
    reciprocalEntityType: "Concept",
    note: "SKOS broaderTransitive / narrowerTransitive",
  },
];

export const AUTHORITY_FIELDS: AuthorityFieldConfig[] = [
  { field: "dc.contributor.author", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Publication / generic contributors" },
  { field: "oairecerif.author.affiliation", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Publication / generic contributors" },
  { field: "dc.contributor.editor", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Publication / generic contributors" },
  { field: "oairecerif.editor.affiliation", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Publication / generic contributors" },
  { field: "dc.relation.product", plugin: "DataSetAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "dc.relation.publication", plugin: "PublicationAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "dc.relation.journal", plugin: "SherpaAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "dc.relation.project", plugin: "ProjectAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "dc.publisher", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Generic" },
  { field: "dc.relation.funding", plugin: "FundingAuthority", presentation: "suggest", controlled: true, externalSource: "fundingAuthority", category: "Relations" },
  { field: "dc.description.sponsorship", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Generic" },
  { field: "crispj.coordinator", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Project" },
  { field: "crispj.organization", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Project" },
  { field: "crispj.partnerou", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Project" },
  { field: "crispj.investigator", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Project" },
  { field: "crispj.coinvestigators", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Project" },
  { field: "dc.relation.equipment", plugin: "EquipmentAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "person.affiliation.name", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Person" },
  { field: "oairecerif.person.affiliation", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Person" },
  { field: "crisrp.qualification", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Person" },
  { field: "crisrp.education", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Person" },
  { field: "organization.parentOrganization", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "OrgUnit" },
  { field: "crisou.director", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "OrgUnit" },
  { field: "oairecerif.funder", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "oairecerif.fundingParent", plugin: "FundingAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "crisfund.investigators", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "crisfund.coinvestigators", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "crisfund.leadorganizations", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "crisfund.leadcoorganizations", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "cris.policy.eperson", plugin: "EPersonAuthority", presentation: "suggest", controlled: true, category: "CRIS / policy" },
  { field: "cris.policy.group", plugin: "GroupAuthority", presentation: "suggest", controlled: true, category: "CRIS / policy" },
  { field: "dspace.object.owner", plugin: "EPersonAuthority", presentation: "suggest", controlled: true, category: "CRIS / policy" },
  { field: "dc.identifier.issn", plugin: "ZDBAuthority", presentation: "suggest", controlled: true, category: "Identifiers" },
  { field: "dc.type", plugin: "ControlledVocabularyAuthority", controlled: true, category: "Generic" },
  { field: "mdwrepo.creator.person", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "mdw" },
  { field: "mdwrepo.publisher.person", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "mdw" },
  { field: "mdwrepo.creator.orgunit", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "mdw" },
  { field: "mdwrepo.publisher.orgunit", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "mdw" },
  { field: "mdwthesis.supervisor.person", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "mdw thesis" },
  { field: "mdwthesis.supervisor.org", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "mdw thesis" },
  { field: "mdwthesis.author.org", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "mdw thesis" },
  { field: "dcat.mdw.relatedDataset", plugin: "DataSetAuthority", presentation: "suggest", controlled: true, category: "DCAT" },
  { field: "dcat.mdw.servedByDataService", plugin: "DataServiceAuthority", presentation: "suggest", controlled: true, category: "DCAT" },
  { field: "dcat.mdw.isInDataCatalog", plugin: "DataCatalogAuthority", presentation: "suggest", controlled: true, category: "DCAT" },
  { field: "dcat.catalog", plugin: "DataCatalogAuthority", presentation: "suggest", controlled: true, category: "DCAT" },
  { field: "dcat.inSeries", plugin: "DataSetAuthority", presentation: "suggest", controlled: true, category: "DCAT" },
  { field: "mdwrepo.memorialBook.competencePlace", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "mdwrepo.person.placeOfBirth", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "mdwrepo.person.placeOfDeath", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "rico.isRelatedTo", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.location", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.hasOrHadParticipant", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.isOrWasAffectedBy", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.affectsOrAffected", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.agentHasOrHadLocation", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.hasOrHadLocation", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.relationHasSource", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.contained", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.containsOrContained", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.wasContainedBy", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.hadPart", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.documentedBy", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "rico.documents", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "RiC-O" },
  { field: "dcat.distribution", plugin: "DcatDistributionProductAuthority", presentation: "suggest", controlled: true, category: "DCAT" },
  { field: "dc.relation.references", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "ebucoreplus.hasCreator", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "EBUCore" },
  { field: "locn.location", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "ebucoreplus.hasProductionDevice", plugin: "EquipmentAuthority", presentation: "suggest", controlled: true, category: "EBUCore" },
  { field: "mdwrepo.isEditedBy", plugin: "MdwPersonAuthority", presentation: "suggest", controlled: true, category: "mdw" },
  { field: "mdwfis.project.coordinatorMdw", plugin: "MdwPersonAuthority", presentation: "suggest", controlled: true, category: "mdw FIS" },
  { field: "dc.creator", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Generic" },
  { field: "mdwlis.function.orgunit", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "mdw LIS" },
  { field: "mdwlis.function.journal", plugin: "JournalAuthority", presentation: "suggest", controlled: true, category: "mdw LIS" },
  { field: "dcterms.isPartOf", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "DCTERMS" },
  { field: "dcterms.isReferencedBy", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "DCTERMS" },
  { field: "dcterms.isReplacedBy", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "DCTERMS" },
  { field: "dcterms.isRequiredBy", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "DCTERMS" },
  { field: "dcterms.isVersionOf", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "DCTERMS" },
  { field: "dcterms.hasVersion", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "DCTERMS" },
  { field: "dcterms.hasPart", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "DCTERMS" },
  { field: "crisou.relation.ispartof", plugin: "CustomItemAuthority", presentation: "suggest", controlled: true, category: "OrgUnit" },
  { field: "dc.relation.event", plugin: "EventAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "dc.relation.conference", plugin: "EventAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "dc.relation.work", plugin: "WorkAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "dc.relation.archivalresource", plugin: "ArchivalResourceAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "dc.contributor.advisor", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Contributors" },
  { field: "dc.contributor.presenter", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Contributors" },
  { field: "dc.contributor.illustrator", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Contributors" },
  { field: "oairecerif.event.place", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Event" },
  { field: "oairecerif.event.country", plugin: "CountryPlaceAuthority", presentation: "suggest", controlled: true, category: "Event" },
  { field: "crisevent.organizerou", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Event" },
  { field: "crisevent.organizerpj", plugin: "ProjectAuthority", presentation: "suggest", controlled: true, category: "Event" },
  { field: "crisevent.sponsorou", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Event" },
  { field: "crisevent.sponsorpj", plugin: "ProjectAuthority", presentation: "suggest", controlled: true, category: "Event" },
  { field: "mdwrepo.venue.name", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "mdwrepo.venue.nameOptional", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "mdwlis.city", plugin: "CityPlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "mdwlis.country", plugin: "ActiveCountryPlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "dcat.dataset", plugin: "DataSetAuthority", presentation: "suggest", controlled: true, category: "DCAT" },
  { field: "dcat.servesDataset", plugin: "DataSetAuthority", presentation: "suggest", controlled: true, category: "DCAT" },
  { field: "dcat.service", plugin: "DataServiceAuthority", presentation: "suggest", controlled: true, category: "DCAT" },
  { field: "dcat.mdw.containsDataset", plugin: "DataSetAuthority", presentation: "suggest", controlled: true, category: "DCAT" },
  { field: "mdwfis.project.previousCoordinator", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "mdw FIS" },
  { field: "mdwfis.recipients.orgUnit", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "mdw FIS" },
  { field: "mdwrepo.orgunit.hasTopOrgUnit", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "OrgUnit" },
  { field: "mdwrepo.isOrWasStudentOf", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Person" },
  { field: "mdwrepo.hasOrHadStudent", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Person" },
  { field: "mdwrepo.isOrWasStudycolleague", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Person" },
  { field: "dc.relation.place", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "mdwrepo.presentation.hostLocation", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Presentation" },
  { field: "mdwrepo.presentation.hostedBy", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Presentation" },
  { field: "mdwlis.soundrecording.isPartOf", plugin: "PublicationAuthority", presentation: "suggest", controlled: true, category: "mdw LIS" },
  { field: "mdwrepo.place.city", plugin: "CityPlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "mdwrepo.place.country", plugin: "CountryPlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "mdwrepo.place.parentPlace", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "dc.relation.orgunit", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Relations" },
  { field: "mdwrepo.event.parentEvent", plugin: "EventAuthority", presentation: "suggest", controlled: true, category: "Event" },
  { field: "organization.address.addressLocality", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "OrgUnit" },
  { field: "organization.address.addressCountry", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "OrgUnit" },
  { field: "risfunding.recipients.orgUnit", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "crisevent.partnerpj", plugin: "ProjectAuthority", presentation: "suggest", controlled: true, category: "Event" },
  { field: "crisevent.partnerou", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Event" },
  { field: "risfunding.recipients.appliedAmountOrgUnit", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "risfunding.recipients.amountOrgUnit", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "mdwfis.project.resubmission", plugin: "ProjectAuthority", presentation: "suggest", controlled: true, category: "mdw FIS" },
  { field: "mdwfis.funding.resubmission", plugin: "FundingAuthority", presentation: "suggest", controlled: true, category: "mdw FIS" },
  { field: "dc.relation.call", plugin: "FundingAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "dc.relation.programme", plugin: "FundingAuthority", presentation: "suggest", controlled: true, category: "Funding" },
  { field: "mdwrepo.archivalresource.parent", plugin: "ArchivalResourceAuthority", presentation: "suggest", controlled: true, category: "ArchivalResource" },
  { field: "mdwrepo.archivalresource.child", plugin: "ArchivalResourceAuthority", presentation: "suggest", controlled: true, category: "ArchivalResource" },
  { field: "lomuibk.relation.resource", plugin: "PublicationAuthority", presentation: "suggest", controlled: true, category: "LOM" },
  { field: "skos.inScheme", plugin: "ConceptSchemeAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.topConceptOf", plugin: "ConceptSchemeAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.hasTopConcept", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.broader", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.broaderTransitive", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.narrower", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.narrowerTransitive", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.related", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.broadMatch", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.closeMatch", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.exactMatch", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.narrowMatch", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "skos.relatedMatch", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "SKOS" },
  { field: "lomuibk.learningresourcetype.entry", plugin: "ConceptAuthority", presentation: "suggest", controlled: true, category: "LOM" },
  { field: "lomuibk.learningresourcetype.entry", plugin: "ConceptHscrtAuthority", presentation: "suggest", controlled: true, category: "LOM" },
  { field: "mdwrepo.ivearchive.genre", plugin: "ConceptIveMusicGenreAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.community", plugin: "ConceptIveCommunitiesAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.instrument", plugin: "ConceptIveInstrumentsAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.ensemble", plugin: "ConceptIveEnsemblesAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.texttype", plugin: "ConceptIveTextTypeAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.danceterms", plugin: "ConceptIveDanceTermsAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.religion", plugin: "ConceptIveReligionAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.region", plugin: "ConceptIveRegionAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.analyticalparams", plugin: "ConceptIveAnalyticalParamsAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.research", plugin: "ConceptIveResearchAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.cultureterms", plugin: "ConceptIveCultureTermsAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.cultureregion", plugin: "ConceptIveCultureRegionAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.epoche", plugin: "ConceptIveEpocheAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.job", plugin: "ConceptIveJobAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.avmedia", plugin: "ConceptIveAVMediaAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.dailylife", plugin: "ConceptIveDailyLifeAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ivearchive.language", plugin: "ConceptIveLanguageAuthority", presentation: "suggest", controlled: true, category: "IVE Archive" },
  { field: "mdwrepo.ensemble.name", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "mdw" },
  { field: "mdwlis.artisticAppearance.event", plugin: "EventAuthority", presentation: "suggest", controlled: true, category: "mdw LIS" },
  { field: "mdwlis.artisticAppearance.organizer", plugin: "PersonOrOrgUnitAuthority", presentation: "suggest", controlled: true, category: "mdw LIS" },
  { field: "dc.contributor.curator", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Contributors" },
  { field: "mdwrepo.contributor.curator", plugin: "CustomPersonAuthority", presentation: "suggest", controlled: true, category: "Contributors" },
  { field: "crisrp.country", plugin: "CountryPlaceAuthority", presentation: "suggest", controlled: true, category: "Person" },
  { field: "dc.coverage.spatial", plugin: "PlaceAuthority", presentation: "suggest", controlled: true, category: "Places" },
  { field: "crispj.funder", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "Project" },
  { field: "crisou.place.country", plugin: "CountryPlaceAuthority", presentation: "suggest", controlled: true, category: "OrgUnit" },
  { field: "orgunit.identifier.country", plugin: "CountryPlaceAuthority", presentation: "suggest", controlled: true, category: "OrgUnit" },
  { field: "mdwrepo.publisher.location", plugin: "CityPlaceAuthority", presentation: "suggest", controlled: true, category: "mdw" },
  { field: "mdwfis.funding.coordinatorMdw", plugin: "MdwPersonAuthority", presentation: "suggest", controlled: true, category: "mdw FIS" },
  { field: "mdwfis.funding.submittingOrgUnit", plugin: "OrgUnitAuthority", presentation: "suggest", controlled: true, category: "mdw FIS" },
  { field: "mdwlis.subject.oefosDeKunstzweig", plugin: "oefos-kunstzweige", presentation: "suggest", controlled: true, category: "Controlled vocabulary" },
];

export const AUTHORITY_FIELDS_BY_NAME: Record<string, AuthorityFieldConfig[]> = AUTHORITY_FIELDS.reduce(
  (acc, entry) => {
    acc[entry.field] ??= [];
    acc[entry.field].push(entry);
    return acc;
  },
  {} as Record<string, AuthorityFieldConfig[]>,
);

export const RECIPROCAL_RELATIONS_BY_FIELD: Record<string, ReciprocalRelation[]> = RECIPROCAL_RELATIONS.reduce(
  (acc, entry) => {
    acc[entry.field] ??= [];
    acc[entry.field].push(entry);
    return acc;
  },
  {} as Record<string, ReciprocalRelation[]>,
);

export function getAuthorityConfigs(field: string): AuthorityFieldConfig[] {
  return AUTHORITY_FIELDS_BY_NAME[field] ?? [];
}

export function getReciprocalRelations(field: string, entityType?: string): ReciprocalRelation[] {
  const matches = RECIPROCAL_RELATIONS_BY_FIELD[field] ?? [];
  return entityType ? matches.filter((entry) => entry.entityType === entityType) : matches;
}

export function isAuthorityControlledField(field: string): boolean {
  return field in AUTHORITY_FIELDS_BY_NAME;
}
